package com.xoftix.xdms.workflow.activiti.tipo;

public enum MessageEventType {

	TASK_ACTIVATED,
	TASK_ASSIGNED,
	TASK_CANCELLED,
	TASK_COMPLETED,
	TASK_CREATED,
	TASK_SUSPENDED,
	PROCESS_CANCELLED,
	PROCESS_COMPLETED,
	PROCESS_CREATED,
	PROCESS_STARTED,
	PROCESS_SUSPENDED;
}
